name: squadmobile_base_project
description: Projeto base padrão da squad in-house mobile para novos desafios em Flutter.

publish_to: 'none'

version: 1.0.0+1

vars:
  runner: flutter pub run build_runner
  clean: flutter clean
  get: flutter pub get

scripts: 
  mobx_build: $runner build --delete-conflicting-outputs
  mobx_watch: $runner watch --delete-conflicting-outputs

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  trust_fall: ^1.0.4
  connectivity: ^0.4.9+3
  mobx: ^1.2.1+2
  shared_preferences: ^0.5.12
  dio: ^3.0.10
  flutter_mobx: ^1.1.0+2
  get_it: ^5.0.3
  uuid: ^2.2.2
  encrypt: ^4.1.0
  data_connection_checker: ^0.3.4
  

dev_dependencies:
  mockito: ^4.1.1
  mobx_codegen: ^1.1.0+1
  build_runner: ^1.10.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    # - assets/images/
    - assets/fonts/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
        - asset: assets/fonts/roboto/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
          weight: 700
